config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do

    unauthenticated do
      root 'registrations#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:show]
  resources :questions, only: [:create, :destroy, :show]
  resources :solutions, only: [:create, :destroy]

  root 'registrations#new'
  get 'contact' => 'pages#contact'
  get 'team' => 'pages#team'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_one :solution
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true
  validate  :picture_size
  validate :enough_question_balance

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB") #this never shows up
    end
  end

  def enough_question_balance
    if self.user.question_balance < 1
      errors.add(:question_balance, "is not enough")
    end
  end


end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :solutions, dependent: :destroy
  validates :password, length: { minimum: 8 }, unless: "password.nil?"
  validates :password, presence: true, if: "id.nil?"
  validates :name, presence: true

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_default_question_balance, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def set_default_question_balance
    self.question_balance ||= 5
  end

  def User.update_question_balance
    User.update_all question_balance = 5
  end

  def use_question!
    self.question_balance -= 1
    save
  end

  def feed
    if admin?
      Question.all
    else
      questions
      #here we'd have to pull each question with it's associated comment...
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || "pt-BR"
  end

  def after_sign_in_path_for(resource)
    edit_user_registration_path(current_user)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def team
  end

  def contact
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      current_user.use_question!
      AdminMailer.new_question_notifier(current_user, @question).deliver_now
      flash[:notice] = "Question created!"
      redirect_to request.referrer || root_url
    else
      @feed_items = []
    render 'users/show'
    end
  end

  def show
    @question = Question.find(params[:id])
    if user_signed_in?
      @user = current_user
      @solution = @user.solutions.build
    end
  end

  def destroy
  end

  private

  def question_params
    params.require(:question).permit(:content, :picture)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:email,
                                 :name,
                                 :school,
                                 :birthday,
                                 :grade,
                                 :city,
                                 :state,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email,
                                 :name,
                                 :school,
                                 :birthday,
                                 :grade,
                                 :city,
                                 :state,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
    if params[@devise_mapping.name][:password_confirmation].blank?
      params[@devise_mapping.name].delete(:password)
      params[@devise_mapping.name].delete(:password_confirmation)
    end
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!

  def create
    solution = current_user.solutions.build(solution_params)
    if solution.save
      question = Question.find(params[:question_id])
      UserMailer.question_replied_notifier(current_user, question).deliver_now
      flash[:notice] = "Solution created!"
    else
      flash[:alert] = "There was an error"
    end
    redirect_to request.referrer || root_url
  end

  def destroy
  end

  private

  def solution_params
    params.require(:solution).permit(:content).merge(question_id: params[:question_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    if user_signed_in?
      @question = @user.questions.build
      @feed_items = current_user.feed
    end
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_tag(&block)
    content_tag :body, yield, class: "#{controller_name}-#{action_name}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
  def br_states
    [["Acre", "AC"],
     ["Alagoas", "AL"],
     ["Amapá", "AP"],
     ["Amazonas", "AM"],
     ["Bahia", "BA"],
     ["Ceará", "CE"],
     ["Distrito Federal", "DF"],
     ["Espírito Santo", "ES"],
     ["Goiás", "GO"],
     ["Maranhão", "MA"],
     ["Mato Grosso", "MT"],
     ["Mato Grosso do Sul", "MS"],
     ["Minas Gerais", "MG"],
     ["Pará", "PA"],
     ["Paraíba", "PB"],
     ["Paraná", "PR"],
     ["Pernambuco", "PE"],
     ["Piauí", "PI"],
     ["Rio de Janeiro", "RJ"],
     ["Rio Grande do Norte", "RN"],
     ["Rio Grande do Sul", "RS"],
     ["Rondônia", "RO"],
     ["Roraima", "RR"],
     ["Santa Catarina", "SC"],
     ["São Paulo", "SP"],
     ["Sergipe", "SE"],
     ["Tocantins", "TO"]]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_aulas.html.erb
<div id="aulas">
  <div class="container">
    <h1>Aulas particulares</h1>
    <div class="jumbotron">
      <h1>Dummy</h1>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Quem somos", team_path %></li>
        <li><%= link_to "Contato", contact_path %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-custom">
  <div class="container">
    <%= link_to "study hall", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to t(".hello", default: "Hello,") + " #{current_user.name}", user_path(current_user), :class => 'navbar-link' %> </li>
            <li><%= link_to t(".profile", default: "Profile"), edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li><%= link_to t(".log_out", default: "Log out"), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
        <% else %>
            <li><%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_landing.html.erb
<div id="landing">
<div class="container">
  <div class="col-md-6">
      <div class="row panel panel-default">
        <h2>Plantão de dúvidas virtual</h2>
        <h4>Ajuda rápida e sem custo dos melhores professores de Sao Paulo.
          Respondemos perguntas de física, química e matemática.</h4>
      </div>
    <div class="row panel panel-default">
      <h2>Como funciona?</h2>
      <h4>Simples! É só fazer a sua inscrição ao lado e postar sua pergunta por foto ou texto.
      Dentro de 48h, postamos a vídeo resposta, e você será notificado por email.</h4>
    </div>
    <div class="row panel panel-default">
      <h2>Quanto custa?</h2>
      <h4>Nada, cada mês você tem direito a 5 perguntas. </h4>
    </div>
  </div>
  <div class="col-md-1">
  </div>
  <div class="col-md-5">
    <div class="panel panel-default">
      Hello
    </div>
  </div>
</div>
</div>

app/views/layouts/_reviews.html.erb
<div id="review">
  <div class="container">
    <h3>"Vel ex eligendi scriptorem,pro dolore facilisi ne, in aperiri detracto ius.
      Modo ceteros contentiones sea ut, nec id putent feugait,
      te ferri lucilius forensibus his.
      Eam fugit utamur blandit ea. Ut sint saperet voluptatum nam.
      Omnes nostro id sea, ea labore intellegam sit."
    </h3>
    <h4>- Some person</h4>
  </div>
</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/_team.html.erb
<div id="team">
  <div class="container">
    <h1>Professora Lara Wada</h1>
    <div class="maintext">
      <div class="media">
        <div class="media-left">
            <%= image_tag('lara.jpg') %>
        </div>
        <div class="media-body">
          <ul class="list-group">
            <li class="list-group-item">Cras justo odio</li>
            <li class="list-group-item">Dapibus ac facilisis in</li>
            <li class="list-group-item">Morbi leo risus</li>
            <li class="list-group-item">Porta ac consectetur ac</li>
            <li class="list-group-item">Vestibulum at eros</li>
          </ul>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyHallWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<%= body_tag do %>
    <%= render 'layouts/header' %>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <!--<%= render 'layouts/footer' %>-->
<% end %>
</html>

app/views/pages/contact.html.erb
<div id="contact">
  <div class="container">
    <h1>Entre em contato</h1>
  </div>
</div>

app/views/pages/team.html.erb
<%= render 'layouts/team' %>
<h2>Atendimento presencial disponivel em unidade em Moema</h2>

app/views/questions/_question.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
<%= link_to(question_path(question.id), class:"list-group-item", id:"question-#{question.id}") do %>
      <%= question.user.name %> |
      <%= question.content if question.content? %>
<% end %>
</div>
<div class="col-md-2"></div>

app/views/questions/_solution_form.html.erb
<%= form_for(@solution) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div><%= hidden_field_tag :question_id, @question.id %></div>
        <div class="field">
          <%= f.text_area :content, placeholder: "Responda aqui...", class:"form-control" %>
        </div>
     <br>
        <%= f.submit "Postar", class: "btn btn-primary" %>
 <% end %>

app/views/questions/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>Pergunta</h1>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="well">
        <%= @question.content %>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="well">
        <%= image_tag @question.picture.url if @question.picture? %>
      </div>
      <h4><%= @question.user.name %> - Postada <%= time_ago_in_words(@question.created_at) %> atrás</h4>
    </div>
    <div class="col-md-2"></div>
  </div>
    <br>
<div class="page-header">
  <h2>Solução</h2>
</div>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <%= render 'solutions/solution' %>
  </div>
  <div class="col-md-2"></div>
</div>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <%= render 'questions/solution_form' if current_user.admin? %>
  </div>
  <div class="col-md-2"></div>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        O formulário contém <%= pluralize(object.errors.count, "erro") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/solutions/_solution.html.erb
<div class="well"><%= @question.solution.content unless @question.solution.nil? %></div>

app/views/users/_feed.html.erb
<% if @feed_items.any? %>
    <div class="questions list-group">
      <%= render @feed_items %>
    </div>
<% end %>

app/views/users/_question_form.html.erb
<%= form_for(@question, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Pergunte aqui...", class: "form-control" %>
    </div>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </br>
    <%= f.submit "Postar", class: "btn btn-success" %>
<% end %>
</div>

<script type="text/javascript">
    $('#question_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/users/show.html.erb
 <% if !current_user.admin? %>
      <div class="row">
        <div class="page-header"><h1>Qual é a sua pergunta?</h1></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= render 'users/question_form' %>
        </div>
        <div class="col-md-2"></div>
      </div>
  <% end %>
  <div class="row">
    <div class="page-header"><h1>Perguntas</h1></div>
  </div>
  <div class="row">
    <%= render 'users/feed' %>
  </div>